import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from './providers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-[#292322]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-[#292322]`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
